on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  skip: false

name: Deploy Extension
jobs:
  Publish:
    name: Publish
    # prevents this action from running on forks
    if: github.repository == 'yxw007/vscode-translate-next'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: master
          fetch-depth: 0

      - name: Use Node.js 22.x
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install build tools
        run: sudo apt-get install -y build-essential

      - name: Install dependencies
        run: npm install --no-frozen-lockfile

      - name: Publish to Visual Studio Marketplace
        if: env.skip == 'false'
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
